// Code generated by tools/typespecgen; DO NOT EDIT.

package value

import "github.com/kud360/goxsd8/xsd"

// primitiveNames is every ·primitive· datatype, in spec order: the 19 of
// Datatypes §3.3, then precisionDecimal (xsd-precisionDecimal.md §3).
var primitiveNames = []xsd.QName{
	{Space: xsd.XMLSchemaNS, Local: "string"},
	{Space: xsd.XMLSchemaNS, Local: "boolean"},
	{Space: xsd.XMLSchemaNS, Local: "decimal"},
	{Space: xsd.XMLSchemaNS, Local: "float"},
	{Space: xsd.XMLSchemaNS, Local: "double"},
	{Space: xsd.XMLSchemaNS, Local: "duration"},
	{Space: xsd.XMLSchemaNS, Local: "dateTime"},
	{Space: xsd.XMLSchemaNS, Local: "time"},
	{Space: xsd.XMLSchemaNS, Local: "date"},
	{Space: xsd.XMLSchemaNS, Local: "gYearMonth"},
	{Space: xsd.XMLSchemaNS, Local: "gYear"},
	{Space: xsd.XMLSchemaNS, Local: "gMonthDay"},
	{Space: xsd.XMLSchemaNS, Local: "gDay"},
	{Space: xsd.XMLSchemaNS, Local: "gMonth"},
	{Space: xsd.XMLSchemaNS, Local: "hexBinary"},
	{Space: xsd.XMLSchemaNS, Local: "base64Binary"},
	{Space: xsd.XMLSchemaNS, Local: "anyURI"},
	{Space: xsd.XMLSchemaNS, Local: "QName"},
	{Space: xsd.XMLSchemaNS, Local: "NOTATION"},
	{Space: xsd.XMLSchemaNS, Local: "precisionDecimal"},
}
