package main

import (
	"os"
	"slices"
	"strings"
	"testing"
)

const (
	testBlocks    = "../../docs/specs/ucd/Blocks-15.0.0.txt"
	testDatatypes = "../../docs/specs/md/xmlschema11-2.md"
	testCommitted = "../../regex/gen_blocks.go"
)

func mustGenerate(t *testing.T) []byte {
	t.Helper()
	src, err := generate(testBlocks, testDatatypes)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	return src
}

// TestDeterministic pins STYLE D1: two generation runs are byte-identical.
func TestDeterministic(t *testing.T) {
	first := mustGenerate(t)
	second := mustGenerate(t)
	if string(first) != string(second) {
		t.Fatal("generate is not byte-identical across runs")
	}
}

// TestCommittedUpToDate fails if regex/gen_blocks.go has drifted from what the
// generator produces — edited by hand, or not regenerated with `go generate
// ./...` after an input changed.
func TestCommittedUpToDate(t *testing.T) {
	want, err := os.ReadFile(testCommitted)
	if err != nil {
		t.Fatalf("reading committed file: %v", err)
	}
	if string(mustGenerate(t)) != string(want) {
		t.Fatalf("%s is stale; run `go generate ./...`", testCommitted)
	}
}

// TestHeaderNamesVersion pins the ·implementation-defined· Unicode version
// (§G.4.2.3) into the generated header, read from the input's own first line.
func TestHeaderNamesVersion(t *testing.T) {
	const want = "// Code generated by tools/blockgen from Unicode 15.0.0 Blocks.txt; DO NOT EDIT.\n"
	if src := string(mustGenerate(t)); !strings.HasPrefix(src, want) {
		t.Fatalf("header = %q, want %q", strings.SplitAfter(src, "\n")[0], want)
	}
}

// TestParseBlocksPinnedInput pins the pinned file's shape: 327 blocks, keyed by
// normalized name (a space dropped, a hyphen kept), first and last in file
// order.
func TestParseBlocksPinnedInput(t *testing.T) {
	text, err := os.ReadFile(testBlocks)
	if err != nil {
		t.Fatalf("reading %s: %v", testBlocks, err)
	}
	version, blocks, err := parseBlocks(strings.Split(string(text), "\n"))
	if err != nil {
		t.Fatalf("parseBlocks: %v", err)
	}
	if version != "15.0.0" {
		t.Errorf("version = %q, want 15.0.0", version)
	}
	if len(blocks) != 327 {
		t.Errorf("%d blocks, want 327", len(blocks))
	}
	first, last := blocks[0], blocks[len(blocks)-1]
	if first != (block{"BasicLatin", runeRange{0x0000, 0x007F}}) {
		t.Errorf("first block = %+v, want BasicLatin 0000..007F", first)
	}
	if last != (block{"SupplementaryPrivateUseArea-B", runeRange{0x100000, 0x10FFFF}}) {
		t.Errorf("last block = %+v, want SupplementaryPrivateUseArea-B 100000..10FFFF", last)
	}
}

// TestParseSupersededFromSpec pins §G.4.2.3's list as read from the local spec:
// three names, PrivateUse at the first of the spec's three ranges only.
func TestParseSupersededFromSpec(t *testing.T) {
	text, err := os.ReadFile(testDatatypes)
	if err != nil {
		t.Fatalf("reading %s: %v", testDatatypes, err)
	}
	got, err := parseSuperseded(strings.Split(string(text), "\n"))
	if err != nil {
		t.Fatalf("parseSuperseded: %v", err)
	}
	want := []block{
		{"Greek", runeRange{0x0370, 0x03FF}},
		{"CombiningMarksforSymbols", runeRange{0x20D0, 0x20FF}},
		{"PrivateUse", runeRange{0xE000, 0xF8FF}},
	}
	if !slices.Equal(got, want) {
		t.Fatalf("superseded = %+v, want %+v", got, want)
	}
}

// TestInputShapeErrors pins that a changed input stops the build rather than
// emitting a short or unreachable table.
func TestInputShapeErrors(t *testing.T) {
	blocks := func(lines ...string) error {
		_, _, err := parseBlocks(lines)
		return err
	}
	cases := []struct {
		name string
		err  error
		want string
	}{
		{"no version line", blocks("0000..007F; Basic Latin"), "does not name the Blocks.txt version"},
		{"malformed entry", blocks("# Blocks-15.0.0.txt", "0000-007F; Basic Latin"), "line 2:"},
		{"reversed range", blocks("# Blocks-15.0.0.txt", "007F..0000; Basic Latin"), "not an interval"},
		{"no entries", blocks("# Blocks-15.0.0.txt", "# comment"), "no block entries"},
		{"key outside [96]", checkKeys([]block{{key: "Latin+1"}}), `"Latin+1" is outside production [96]`},
		{"duplicate key", checkKeys([]block{{key: "Greek"}, {key: "Greek"}}), `"Greek" appears twice`},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if c.err == nil || !strings.Contains(c.err.Error(), c.want) {
				t.Fatalf("err = %v, want one containing %q", c.err, c.want)
			}
		})
	}
	if _, err := parseSuperseded([]string{"no list here"}); err == nil {
		t.Error("parseSuperseded found a list in text without one")
	}
}
