// Command typespecgen emits builtin/gen_typespec.go: the backend-neutral
// TypeSpec table for all 49 builtin datatypes. It is the Go-emission half of
// the M1 builtin pipeline (PRINCIPLES 26/27); all spec parsing lives in
// tools/hfnextract/builtins, which this command consumes. Output is gofmt'd
// and deterministic, so running it twice is byte-identical (STYLE D1).
//
// With -primitives it emits value/gen_primitives.go instead: the unexported
// primitiveNames slice of the 20 ·primitive· datatype QNames (the 19 of
// Datatypes §3.3 plus precisionDecimal), which value.ConstraintMatches scans as
// a ·special· type's lexical-mapping union (Datatypes §3.2.1.2, §3.2.2.2).
// Package value cannot import package builtin, which imports it.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"

	"github.com/kud360/goxsd8/tools/hfnextract/builtins"
)

func main() {
	structuresPath := flag.String("structures", "docs/specs/md/xmlschema11-2.md", "Datatypes spec Markdown")
	precisionPath := flag.String("precision", "docs/specs/md/xsd-precisionDecimal.md", "precisionDecimal Note Markdown")
	outPath := flag.String("out", "builtin/gen_typespec.go", "output Go file")
	primitives := flag.Bool("primitives", false, "emit package value's primitiveNames slice instead of the TypeSpec table")
	flag.Parse()

	if err := run(*structuresPath, *precisionPath, *outPath, *primitives); err != nil {
		fmt.Fprintf(os.Stderr, "typespecgen: %v\n", err)
		os.Exit(1)
	}
}

func run(structuresPath, precisionPath, outPath string, primitives bool) error {
	types, err := builtins.Parse(structuresPath, precisionPath)
	if err != nil {
		return err
	}
	emitter := emit
	if primitives {
		emitter = emitPrimitives
	}
	src, err := emitter(types)
	if err != nil {
		return err
	}
	return os.WriteFile(outPath, src, 0o644)
}

func emit(types []builtins.Builtin) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/typespecgen; DO NOT EDIT.\n\n")
	b.WriteString("package builtin\n\n")
	b.WriteString("// Types is the backend-neutral table of all 49 builtin datatypes, in\n")
	b.WriteString("// spec order: the 19 primitives (§3.3), the 28 ordinary datatypes (§3.4),\n")
	b.WriteString("// anyAtomicType (§3.2.2), then precisionDecimal (xsd-precisionDecimal.md §3).\n")
	b.WriteString("// anySimpleType is excluded: it has no facets and cannot be a restriction\n")
	b.WriteString("// base (§3.2.1.3).\n")
	b.WriteString("var Types = []TypeSpec{\n")
	for _, t := range types {
		if err := emitType(&b, t); err != nil {
			return nil, err
		}
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w", err)
	}
	return src, nil
}

// primitiveCount is the number of ·primitive· datatypes: the 19 of Datatypes
// §3.3 plus precisionDecimal (xsd-precisionDecimal.md §3).
const primitiveCount = 20

// emitPrimitives emits package value's primitiveNames: every atomic builtin
// whose base is anyAtomicType (§4.1.6 dummy-def), in spec order. anyAtomicType
// itself derives from anySimpleType, so it is not one of them.
func emitPrimitives(types []builtins.Builtin) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/typespecgen; DO NOT EDIT.\n\n")
	b.WriteString("package value\n\n")
	b.WriteString("import \"github.com/kud360/goxsd8/xsd\"\n\n")
	b.WriteString("// primitiveNames is every ·primitive· datatype, in spec order: the 19 of\n")
	b.WriteString("// Datatypes §3.3, then precisionDecimal (xsd-precisionDecimal.md §3).\n")
	b.WriteString("var primitiveNames = []xsd.QName{\n")
	n := 0
	for _, t := range types {
		if t.Base != "anyAtomicType" || t.Variety != "atomic" {
			continue
		}
		fmt.Fprintf(&b, "\t{Space: xsd.XMLSchemaNS, Local: %q},\n", t.Name)
		n++
	}
	b.WriteString("}\n")
	if n != primitiveCount {
		return nil, fmt.Errorf("found %d primitive datatypes, want %d", n, primitiveCount)
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w", err)
	}
	return src, nil
}

func emitType(b *strings.Builder, t builtins.Builtin) error {
	variety, err := varietyLit(t)
	if err != nil {
		return fmt.Errorf("%s: %w", t.Name, err)
	}
	fund, err := fundamental(t)
	if err != nil {
		return fmt.Errorf("%s: %w", t.Name, err)
	}

	fmt.Fprintf(b, "\t{\n")
	fmt.Fprintf(b, "\t\tName:    %q,\n", t.Name)
	fmt.Fprintf(b, "\t\tBase:    %q,\n", t.Base)
	fmt.Fprintf(b, "\t\tVariety: %s,\n", variety)
	// fund == "" is the empty {fundamental facets}: leave Fundamental nil.
	if fund != "" {
		fmt.Fprintf(b, "\t\tFundamental: %s,\n", fund)
	}
	if len(t.Facets) > 0 {
		fmt.Fprintf(b, "\t\tFacets: []Facet{\n")
		for _, f := range t.Facets {
			b.WriteString("\t\t\t{")
			fmt.Fprintf(b, "Name: %q", f.Name)
			if f.Value != "" {
				fmt.Fprintf(b, ", Default: %q", f.Value)
			}
			if f.Fixed {
				b.WriteString(", Fixed: true")
			}
			b.WriteString("},\n")
		}
		fmt.Fprintf(b, "\t\t},\n")
	}
	fmt.Fprintf(b, "\t},\n")
	return nil
}

// varietyLit emits the sealed Variety branch: Atomic{} for atomic types,
// List{Item: "..."} for lists (§4.1.1).
func varietyLit(t builtins.Builtin) (string, error) {
	switch t.Variety {
	case "atomic":
		return "Atomic{}", nil
	case "list":
		return fmt.Sprintf("List{Item: %q}", t.Item), nil
	}
	return "", fmt.Errorf("unknown variety %q", t.Variety)
}

// fundamental emits the &Fundamental{...} literal, or "" to signal the empty
// {fundamental facets} (anyAtomicType alone), for which the caller leaves the
// nil pointer. All four inputs empty is that all-or-nothing empty case (§4.2);
// a partial mix is a parser bug and errors below.
func fundamental(t builtins.Builtin) (string, error) {
	if t.Ordered == "" && t.Bounded == "" && t.Cardinality == "" && t.Numeric == "" {
		return "", nil
	}
	ordered, err := lookup(orderedConst, t.Ordered)
	if err != nil {
		return "", fmt.Errorf("ordered: %w", err)
	}
	bounded, err := lookup(boundedConst, t.Bounded)
	if err != nil {
		return "", fmt.Errorf("bounded: %w", err)
	}
	card, err := lookup(cardinalityConst, t.Cardinality)
	if err != nil {
		return "", fmt.Errorf("cardinality: %w", err)
	}
	numeric, err := lookup(numericConst, t.Numeric)
	if err != nil {
		return "", fmt.Errorf("numeric: %w", err)
	}
	return fmt.Sprintf("&Fundamental{Ordered: %s, Bounded: %s, Cardinality: %s, Numeric: %s}", ordered, bounded, card, numeric), nil
}

func lookup(m map[string]string, token string) (string, error) {
	c, ok := m[token]
	if !ok {
		return "", fmt.Errorf("unknown value %q", token)
	}
	return c, nil
}

// The maps translate the spec tokens the parser reports into the Go constants
// in builtin/typespec.go. There is no "" entry: an empty {fundamental facets}
// is handled whole in fundamental (nil *Fundamental), never per field, so a
// stray empty token on one facet is a caught error rather than an absent value.
var (
	orderedConst     = map[string]string{"false": "OrderedFalse", "partial": "OrderedPartial", "total": "OrderedTotal"}
	boundedConst     = map[string]string{"false": "BoundedFalse", "true": "BoundedTrue"}
	cardinalityConst = map[string]string{"finite": "CardinalityFinite", "countably infinite": "CardinalityCountablyInfinite"}
	numericConst     = map[string]string{"false": "NumericFalse", "true": "NumericTrue"}
)
