package main

import (
	"fmt"
	"go/format"
	"strings"
)

// xsdNamespace is the XML Schema namespace every builtin QName carries.
const xsdNamespace = "http://www.w3.org/2001/XMLSchema"

// emit renders the vectors table as gofmt'd Go source for package backendtest.
func emit(types []typeVectors) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/backendtestgen; DO NOT EDIT.\n\n")
	b.WriteString("package backendtest\n\n")
	b.WriteString(`import "github.com/kud360/goxsd8/xsd"` + "\n\n")
	b.WriteString("// vectors is the spec-derived conformance corpus value/backendtest.Run\n")
	b.WriteString("// drives every value.Backend through (PRINCIPLES 26). Each row is one\n")
	b.WriteString("// builtin type's lexical/canonical vectors. M3 covers boolean only.\n")
	b.WriteString("var vectors = []typeVectors{\n")
	for _, t := range types {
		emitType(&b, t)
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w", err)
	}
	return src, nil
}

func emitType(b *strings.Builder, t typeVectors) {
	b.WriteString("\t{\n")
	fmt.Fprintf(b, "\t\tTyp: xsd.QName{Space: %q, Local: %q},\n", xsdNamespace, t.Local)
	if len(t.Valid) > 0 {
		b.WriteString("\t\tValid: []roundtrip{\n")
		for _, rt := range t.Valid {
			fmt.Fprintf(b, "\t\t\t{Lexical: %q, Canonical: %q},\n", rt.Lexical, rt.Canonical)
		}
		b.WriteString("\t\t},\n")
	}
	if len(t.Invalid) > 0 {
		b.WriteString("\t\tInvalid: []string{\n")
		for _, lex := range t.Invalid {
			fmt.Fprintf(b, "\t\t\t%q,\n", lex)
		}
		b.WriteString("\t\t},\n")
	}
	if len(t.NarrowReject) > 0 {
		b.WriteString("\t\tNarrowReject: []string{\n")
		for _, lex := range t.NarrowReject {
			fmt.Fprintf(b, "\t\t\t%q,\n", lex)
		}
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t},\n")
}
