package main

import (
	"fmt"
	"go/format"
	"strings"
)

// emit renders the vectors table as gofmt'd Go source for package backendtest.
func emit(types []typeVectors) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/backendtestgen; DO NOT EDIT.\n\n")
	b.WriteString("package backendtest\n\n")
	b.WriteString(`import "github.com/kud360/goxsd8/xsd"` + "\n\n")
	b.WriteString("// vectors is the spec-derived conformance corpus value/backendtest.Run\n")
	b.WriteString("// drives every value.Backend through (PRINCIPLES 26). Each row is one\n")
	b.WriteString("// builtin type's lexical/canonical vectors plus its applicable constraining\n")
	b.WriteString("// facets in spec order (cos-applicable-facets). The cohort covers boolean,\n")
	b.WriteString("// decimal, string, float, double, hexBinary, base64Binary, duration, dateTime\n")
	b.WriteString("// and the seven-property siblings time, date, gYearMonth, gYear, gMonthDay,\n")
	b.WriteString("// gDay and gMonth.\n")
	b.WriteString("var vectors = []typeVectors{\n")
	for _, t := range types {
		emitType(&b, t)
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w", err)
	}
	return src, nil
}

func emitType(b *strings.Builder, t typeVectors) {
	b.WriteString("\t{\n")
	// Emit the exported xsd.XMLSchemaNS identifier, not the raw literal: the
	// generated file already imports xsd (for xsd.QName), so referencing the
	// shared constant de-duplicates the namespace string (STYLE D3).
	fmt.Fprintf(b, "\t\ttyp: xsd.QName{Space: xsd.XMLSchemaNS, Local: %q},\n", t.Local)
	if len(t.Valid) > 0 {
		b.WriteString("\t\tvalid: []roundtrip{\n")
		for _, rt := range t.Valid {
			fmt.Fprintf(b, "\t\t\t{lexical: %q, canonical: %q},\n", rt.Lexical, rt.Canonical)
		}
		b.WriteString("\t\t},\n")
	}
	if len(t.Invalid) > 0 {
		b.WriteString("\t\tinvalid: []string{\n")
		for _, lex := range t.Invalid {
			fmt.Fprintf(b, "\t\t\t%q,\n", lex)
		}
		b.WriteString("\t\t},\n")
	}
	if len(t.NarrowReject) > 0 {
		b.WriteString("\t\tnarrowReject: []string{\n")
		for _, lex := range t.NarrowReject {
			fmt.Fprintf(b, "\t\t\t%q,\n", lex)
		}
		b.WriteString("\t\t},\n")
	}
	if len(t.ApplicableFacets) > 0 {
		b.WriteString("\t\tapplicableFacets: []string{\n")
		for _, f := range t.ApplicableFacets {
			fmt.Fprintf(b, "\t\t\t%q,\n", f)
		}
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t},\n")
}
