// Package xsderr is the error currency of the module: structured errors
// that carry a spec validation rule ID and a source location.
//
// It is a pure leaf — stdlib imports only. Every schema- or
// instance-validity violation the spec CATALOGS is an *Error carrying that
// catalog's rule ID (STYLE E2); free-form errors are for I/O faults,
// programming faults, and the one validity class the spec catalogs nowhere,
// below.
//
// # The s4s-grammar class
//
// A schema document that is simply not valid against the schema for schema
// documents — a prohibited or missing attribute, a child its content model
// does not admit, one repeated past its maxOccurs, one out of order —
// violates §2.4 clause 1 (sd-valid, xmlschema11-1.md:615). That clause is
// anchored but uncataloged: it is absent from Appendix B's three tables
// (B.1 cvc-*, B.3 src-*, B.4 cos-*), which are the spec's own exhaustive
// lists of citable codes, and §5.1's restatement of it (:4296) carries no
// anchor at all. No src-* covers the grammar either, by construction:
// §2.3's gloss-src (:607) defines Schema Representation Constraints as
// constraints "beyond those which are expressed in" that grammar, and every
// src-* with sub-clauses opens "In addition to the conditions imposed ...
// by the schema for schema documents" (src-ct, :1946; src-ta, :3218).
//
// So a rejection in this class carries no Rule and is not an *Error at all.
// It is a plain error whose message names the offending item, its location
// and the Appendix A production it violates — parser's
// rejectProhibitedAttrs and checkS4SChildOrder are the shape to copy. Do
// not charge it sd-valid, which is not a catalog ID and would read as one
// in the Rule position, and do not borrow the nearest src-*, which states a
// different constraint (#966).
//
// # Contract (implemented in M2)
//
//	type Rule string
//	    A spec rule ID: "cvc-complex-type", "cos-st-restricts",
//	    "src-resolve", "derivation-ok-restriction". Exactly one rule per
//	    error. Usually a validation rule; see Rule's own doc for the case
//	    where the spec names a check and states no rule for it.
//
//	const RuleXMLWellFormed Rule = "xml-wf"
//	const RuleComponentInvariant Rule = "component-invariant"
//	    The two non-spec sentinel Rules, for faults that are not schema- or
//	    instance-validity violations and so have no cvc-*/src-* ID but must
//	    still carry a recognizable, non-empty Rule: XML well-formedness
//	    faults (unbound prefixes, mismatched/unclosed tags, malformed XML),
//	    and component-constructor rejections of a state the XML mapping
//	    makes unrepresentable rather than any numbered clause forbidding.
//	    IsValidRule accepts both. The set stays closed at two: the
//	    s4s-grammar class above is the converse case — a real validity
//	    verdict the spec declines to catalog, not a non-validity fault — and
//	    gets no sentinel, because a Rule minted for it would be read as a
//	    citation of a rule the spec does not state.
//
//	type Loc struct { URI string; Line, Col int }
//	    Where the offending construct lives — the schema document or the
//	    instance document. Threaded from parser/xmltree positions, never
//	    reconstructed (STYLE E3). The zero Loc means "location unknown"
//	    and should be rare.
//
//	type Error struct { Rule Rule; Loc Loc; Msg string; Err error }
//	    Error() renders "loc: [rule] msg"; Unwrap() returns Err so
//	    errors.Is/As reach through wrapping (a wrapper that hides its
//	    cause breaks sentinel detection up the chain).
//
//	func New(rule Rule, loc Loc, format string, args ...any) *Error
//	func Wrap(rule Rule, loc Loc, err error) *Error
//	    Wrap attaches a rule and location to a deeper plain error,
//	    preserving its message verbatim and its identity via Unwrap.
//
//	func RuleOf(err error) (Rule, bool)
//	func LocOf(err error) (Loc, bool)
//	    errors.As-based narrowing for callers that hold a plain error.
//
// # The rule catalog
//
// catalog.go is generated by `go tool rulecat` from docs/specs/md: every
// rule ID that appears in the local specs, as the ruleCatalog lookup set.
// IsValidRule(Rule) bool is hand-written in error.go (not generated) so it
// can admit the non-spec sentinels alongside the generated catalog without
// regeneration clobbering those exemptions. Membership is exact — no
// clause-suffix leniency; see IsValidRule. Rule is a bare string type, so
// nothing in the Go type system stops an arbitrary one; the guarantee is
// enforced by test instead. rulecatalog_enforcement_test.go scans the whole
// module for two things: every constant declared with type Rule anywhere in the
// module must satisfy IsValidRule, and in non-test code no string literal may
// sit in one of four syntactic Rule positions — the first argument of New or
// Wrap, the Rule field of an Error composite literal, a return in a function
// whose declared result type is Rule, or the operand of a Rule(...) conversion.
// So a rule the spec doesn't define is caught wherever it is written as a Rule
// constant or as a literal in those four positions. That is a syntactic floor,
// not a dataflow proof: a Rule that reaches New/Wrap through a variable or
// another expression is not scanned, and the test's header comment names the
// residual holes it deliberately leaves open. The generate directive
// (`//go:generate go tool rulecat`) is wired here in M2 together with the
// Rule type it emits against.
package xsderr
