// Code generated by tools/backendtestgen; DO NOT EDIT.

package backendtest

import "github.com/kud360/goxsd8/xsd"

// vectors is the spec-derived conformance corpus value/backendtest.Run
// drives every value.Backend through (PRINCIPLES 26). Each row is one
// builtin type's lexical/canonical vectors. M3 covers boolean only.
var vectors = []typeVectors{
	{
		typ: xsd.QName{Space: "http://www.w3.org/2001/XMLSchema", Local: "boolean"},
		valid: []roundtrip{
			{lexical: "true", canonical: "true"},
			{lexical: "false", canonical: "false"},
			{lexical: "1", canonical: "true"},
			{lexical: "0", canonical: "false"},
		},
		invalid: []string{
			"True",
			"TRUE",
			"False",
			"FALSE",
			"",
			"2",
		},
	},
}
