package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
)

const (
	srcDir    = "docs/specs/md"
	outPath   = "xsderr/catalog.go"
	ruleRegex = `\b(cvc|cos|src)-[a-zA-Z0-9\._-]+`
)

func main() {
	re := regexp.MustCompile(ruleRegex)
	rulesMap := make(map[string]struct{})

	files, err := os.ReadDir(srcDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "reading spec dir %s: %v\n", srcDir, err)
		os.Exit(1)
	}

	for _, file := range files {
		if filepath.Ext(file.Name()) != ".md" {
			continue
		}

		path := filepath.Join(srcDir, file.Name())
		content, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "reading file %s: %v\n", path, err)
			os.Exit(1)
		}

		matches := re.FindAllString(string(content), -1)
		for _, m := range matches {
			rulesMap[m] = struct{}{}
		}
	}

	var sortedRules []string
	for r := range rulesMap {
		sortedRules = append(sortedRules, r)
	}
	sort.Strings(sortedRules)

	f, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "creating output file %s: %v\n", outPath, err)
		os.Exit(1)
	}

	if err := writeCatalog(f, sortedRules); err != nil {
		fmt.Fprintf(os.Stderr, "writing catalog to %s: %v\n", outPath, err)
		_ = f.Close()
		os.Exit(1)
	}

	if err := f.Close(); err != nil {
		fmt.Fprintf(os.Stderr, "closing output file %s: %v\n", outPath, err)
		os.Exit(1)
	}
}

func writeCatalog(f *os.File, rules []string) error {
	lines := []string{
		"// Code generated by tools/rulecat; DO NOT EDIT.\n",
		"\n",
		"package xsderr\n",
		"\n",
		"// ruleCatalog contains all normative validation rule IDs extracted from the specs.\n",
		"var ruleCatalog = map[Rule]struct{}{\n",
	}

	for _, r := range rules {
		lines = append(lines, fmt.Sprintf("\t%q: {},\n", r))
	}
	lines = append(lines, "}\n")

	lines = append(lines, "\n")
	lines = append(lines, "// IsValidRule returns true if the provided rule identifier is defined in the spec catalog.\n")
	lines = append(lines, "func IsValidRule(r Rule) bool {\n")
	lines = append(lines, "\t_, ok := ruleCatalog[r]\n")
	lines = append(lines, "\treturn ok\n")
	lines = append(lines, "}\n")

	for _, line := range lines {
		if _, err := fmt.Fprint(f, line); err != nil {
			return err
		}
	}
	return nil
}
